name: kicker_board
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.3.1
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  formz: ^0.4.1
  riverpod_annotation: ^1.1.1
  dio: ^4.0.6
  retrofit_generator: ^4.2.0
  json_serializable: ^6.6.0
  shared_preferences: ^2.0.17

dev_dependencies:
  freezed: ^2.3.2
  riverpod_generator: ^1.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

